/**
 * @file sendMessage.usecase.ts
 * @module Chat/Application
 * @layer Application
 * @description Send Message Use Case
 */

import { Message, MessageType } from '../../domain/entities/message.entity';
import { IMessageRepository } from '../../domain/repositories/IMessageRepository';
import { IConversationRepository } from '../../domain/repositories/IConversationRepository';
import { ChatNotificationService } from '../../infrastructure/notifications/chatNotification.service';
import { prisma } from '../../../../shared/infra/prisma/prismaClient';
import { CreateNotificationUseCase } from '../../../notifications/application/usecases/createNotification.usecase';
import { NotificationType } from '../../../notifications/domain/entities/notification.entity';

export class SendMessageUseCase {
  private notificationService: ChatNotificationService;

  constructor(
    private readonly messageRepository: IMessageRepository,
    private readonly conversationRepository: IConversationRepository,
    private readonly createNotificationUseCase: CreateNotificationUseCase
  ) {
    this.notificationService = new ChatNotificationService();
  }

  async execute(input: {
    conversationId: string;
    senderId: string;
    content: string;
    type?: MessageType;
  }): Promise<Message> {
    // Security: Check if sender is soft-deleted
    const sender = await prisma.user.findUnique({
      where: { id: input.senderId },
      select: { isDeleted: true },
    });
    
    if (!sender || sender.isDeleted) {
      throw new Error('User account is deleted or not found');
    }

    // Verify conversation exists
    const conversation = await this.conversationRepository.findById(input.conversationId);
    if (!conversation) {
      throw new Error('Conversation not found');
    }

    // Verify sender is participant
    const isParticipant = await this.conversationRepository.isParticipant(
      input.conversationId,
      input.senderId
    );
    if (!isParticipant) {
      throw new Error('User is not a participant in this conversation');
    }

    // Security: Check if users are blocked
    const participants = await this.conversationRepository.getParticipants(input.conversationId);
    const otherParticipantIds = participants
      .filter(p => p.userId !== input.senderId)
      .map(p => p.userId);

    for (const otherUserId of otherParticipantIds) {
      const isBlocked = await this.checkIfUsersBlocked(input.senderId, otherUserId);
      if (isBlocked) {
        throw new Error('Cannot send message to blocked user');
      }
    }

    // Create message entity with validation
    const message = Message.create({
      id: '', // Will be generated by repository
      conversationId: input.conversationId,
      senderId: input.senderId,
      content: input.content,
      type: input.type || MessageType.TEXT,
    });

    // Save message
    const savedMessage = await this.messageRepository.create(message);

    // Update conversation's last message timestamp
    await this.conversationRepository.updateLastMessageAt(
      input.conversationId,
      savedMessage.createdAt
    );

    // Send database notification and push (fail silently)
    this.sendNotificationAsync(savedMessage, input.senderId, otherParticipantIds);

    return savedMessage;
  }

  /**
   * Send database notification and push asynchronously (non-blocking)
   */
  private async sendNotificationAsync(
    message: Message,
    senderId: string,
    recipientIds: string[]
  ): Promise<void> {
    try {
      // Get sender name for notification
      const sender = await prisma.user.findUnique({
        where: { id: senderId },
        select: { name: true },
      });

      if (!sender) {
        return;
      }

      const messagePreview = this.getMessagePreview(message.content, message.type);

      // Send notification to each recipient
      // CreateNotificationUseCase handles:
      // - Database notification record
      // - FCM push (fire-and-forget)
      // - Self-notification prevention
      for (const recipientId of recipientIds) {
        await this.createNotificationUseCase.execute({
          userId: recipientId,
          actorId: senderId,
          type: NotificationType.MESSAGE,
          entityId: message.conversationId,
          title: 'New message',
          body: `${sender.name}: ${messagePreview}`,
        });
      }
    } catch (error) {
      // Fail silently - notifications should never break chat
      console.error('[SendMessage] Notification error:', error);
    }
  }

  /**
   * Get message preview for notification
   */
  private getMessagePreview(content: string | null, type: string): string {
    if (type === MessageType.IMAGE) {
      return '📷 Photo';
    }
    if (type === MessageType.AUDIO) {
      return '🎤 Audio';
    }
    if (!content) {
      return 'Sent a message';
    }
    return content.length > 50 ? content.substring(0, 50) + '...' : content;
  }

  /**
   * Check if two users have blocked each other
   */
  private async checkIfUsersBlocked(userId1: string, userId2: string): Promise<boolean> {
    const blockedFriendship = await prisma.friendship.findFirst({
      where: {
        OR: [
          { userId: userId1, friendId: userId2, status: 'blocked' },
          { userId: userId2, friendId: userId1, status: 'blocked' },
        ],
      },
    });

    return blockedFriendship !== null;
  }
}
